version: '3.8'
services:
    container_a:
      hostname: container_a
      container_name: container_a
      build:
        context: ./
        dockerfile: Dockerfile.containerA
      networks:
        - my-network
      stdin_open: true
      tty: true
    
    # nginx:
    #   hostname: nginx
    #   container_name: nginx
    #   build: 
    #       context: ./
    #       dockerfile: Dockerfile.container_nginx
    #   networks:
    #     - my-network

    nginx:
      hostname: nginx
      container_name: nginx
      build: 
          context: ./
          dockerfile: Dockerfile.container_react_nginx
      ports:
        - "3000:80"
      networks:
        - my-network

    postgres:
      hostname: pgsql
      container_name: pgsql
      build: 
        context: ./postgres-db
        dockerfile: Dockerfile.container_psql
      networks:
        - my-network

    container_b: 
      container_name: container_b
      build: 
        context: ./
        dockerfile: Dockerfile.containerB
      networks:
        - my-network
      ports:
        - "7777:7777"     
      tty: true
      stdin_open: true   

networks:
      my-network: {}






    # container_scrape:
    #   build:
    #       context: ./
    #       dockerfile: Dockerfile.container_scrape
    #   ports:
    #     - "7777:7777"     
    #   tty: true
    #   stdin_open: true    

 
