FROM python:3.9
WORKDIR /app

COPY api/requirements.txt api/api.py api/.flaskenv api/.env api/gunicorn_conf.py api/init.db ./ 
RUN pip install -r ./requirements.txt

EXPOSE 7777
# CMD ["flask", "run"]
CMD ["gunicorn","--config", "gunicorn_conf.py","api:app"]
