FROM node:16-alpine as react-build-step
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH
COPY my-app/package.json my-app/package-lock.json ./
COPY my-app/src ./src
copy my-app/public ./public
RUN npm install
RUN npm run build


FROM nginx:stable-alpine
COPY --from=react-build-step /app/build /usr/share/nginx/html
COPY nginx.default.conf /etc/nginx/conf.d/default.conf
