FROM python:3.9
WORKDIR /app

COPY scrape-test/requirements.txt scrape-test/scrape-api.py scrape-test/scraper.py scrape-test/output.csv scrape-test/.flaskenv ./
RUN pip install --trusted-host pypi.python.org -r requirements.txt

RUN apt-get update && apt-get install -y wget unzip && \
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    apt install -y ./google-chrome-stable_current_amd64.deb && \
    rm google-chrome-stable_current_amd64.deb && \
    apt-get clean

EXPOSE 7777
CMD ["flask", "run"]




